<ScreenOne>:
    label: label_id
    text_input: text_input_id
    button: button_id
    BoxLayout:
        orientation: 'vertical'
        Label:
            id: label_id
            text: 'Введите слово или фразу на английском языке в поле ниже этого текста'
        TextInput:
            id: text_input_id
            font_size: 150
            height: 100
            pos_hint: {'center_x': 0.5, 'center_y': 0.705}
            size_hint: 0.95, 0.5
        Button:
            id: button_id
            text: 'Поиск'
            on_press:
                root.search_video()
                root.manager.transition.direction = 'left'
                root.manager.transition.duration = 1
                root.manager.current = 'screen_two'

<ScreenTwo>:
    BoxLayout:
        VideoPlayer:
            source: root.get_videos()[0]
            state: 'stop'
        VideoPlayer:
            source: root.get_videos()[1]
            state: 'stop'
        VideoPlayer:
            source: root.get_videos()[2]
            state: 'stop'
